default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_boilerplate_development

test:
  <<: *default
  database: rails_api_boilerplate_test

production:
  <<: *default
  database: rails_api_boilerplate_production
  username: rails_api_boilerplate
  password: <%= ENV["RAILS_API_BOILERPLATE_DATABASE_PASSWORD"] %>
